//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDatabaseFirst.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int ID { get; set; }
        public int Route_ID { get; set; }
        public int AirlineOwner { get; set; }
        public int AirlineUser { get; set; }
    
        public virtual AirLine AirLine { get; set; }
        public virtual AirLine AirLine1 { get; set; }
        public virtual Route Route { get; set; }
    }
}
